### PR TITLE
Added missing ajx gif

### PR DESCRIPTION
**Pull request by hughkelsey**
I noticed this was missing from your project. Thanks for setting it up, super useful!

### CODE REVIEW

**Comment by 75lb** [comment]
thanks Hugh.. working with your fork until this gets pulled..

**Comment by jhilden** [comment]
we encountered the same problem.  please merge this pull request and release new version.

**Comment by ralph** [comment]
+1

**Comment by aminariana** [comment]
+10

**Comment by ralph** [comment]
Still using a custom built gem based on @hughkelsey's fork. The fix is pretty straightforward, any reason why this isn't merged into the official master yet?

**Comment by hamorim** [comment]
Using a custom built gem based on @hughkelsey's fork too.

**Comment by tscolari** [comment]
Guys, i'm really sorry.
I don't know why, but I didn't get a notification from this pull request.
I saw it just now, because of other issue that came yesterday.

I released a 1.1.1 version, updating the jquery mobile javascripts, stylesheets and images. The loading gif should be there.
If this still a issue please, update the pull request and I will merge it.

**Comment by aminariana** [comment]
Hallelujah Tiago! Looking forward to a less fragmented world.

**Comment by tscolari** [comment]
I'm really, really sorry :(

The notification setting was off, I don't know why

**Comment by hughkelsey** [comment]
It looks like this isn't fixed in your update. I switched to your 1.1.1 gem and the loader disappeared, merged your changes in to my branch and it was back.

Your code has ajax-loader.png but the file is ajax-loader.gif. This pull request may still resolve the issue or if you've moved to far ahead with 1.1.1 it may be easiest to just fix it yourself.

**Comment by tscolari** [comment]
I believe now it's ok.
Before the ajax-loader.gif was present, but the rake task updated only the .png files in the css.
Now it should work properly with gifs too.

Please try out the last version.

**Comment by hughkelsey** [comment]
Confirmed your 1.1.1.1 seams to have it fixed.

**Pull request closed without merging**
